const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');const os=require('node:os');const sharp=require('sharp');
const {Catalog,safeCopy,digest}=require('../dist-electron/library');const {bestN,groupBursts,photoUrl,photoPath}=require('../dist-electron/model');
async function fixture(){const root=await fs.mkdtemp(path.join(os.tmpdir(),'lpv-test-'));const dir=path.join(root,'source');await fs.mkdir(dir);await sharp({create:{width:240,height:180,channels:3,background:'#f07778'}}).jpeg().toFile(path.join(dir,'DSC001.JPG'));return{root,dir}}
test('URLs preserve case, spaces and punctuation',()=>{const p='/Photos/Lucci’s photo #1.JPG';assert.equal(photoPath(photoUrl(p)),p)})
test('bursts and best N preserve quality while varying selections',()=>{const base={signature:Array(256).fill(100),flag:'none'};const a={...base,id:'a',stem:'1',score:5,capturedAt:'2026-09-04T12:00:00Z'},b={...base,id:'b',stem:'2',score:4.9,capturedAt:'2026-09-04T12:00:01Z'},c={...base,id:'c',stem:'3',score:4.5,signature:Array(256).fill(200),capturedAt:'2026-09-04T12:00:10Z'};groupBursts([a,b,c]);assert.equal(a.burstId,b.burstId);assert.notEqual(a.burstId,c.burstId);assert.deepEqual(bestN([a,b,c],2,0),['a','b']);assert.deepEqual(bestN([a,b,c],2,1),['a','c']);assert.equal(bestN([{...a,flag:'reject'},b],5,1).length,1)})
test('copies never overwrite an existing destination',async()=>{const {root,dir}=await fixture();try{const src=path.join(dir,'DSC001.JPG'),dst=path.join(root,'copy.JPG');await safeCopy(src,dst);const before=await digest(dst);await assert.rejects(safeCopy(src,dst));assert.equal(await digest(dst),before)}finally{await fs.rm(root,{recursive:true,force:true})}})
test('reference project rebuilds previews after cache deletion, preserves edits, and exports with conflicts',async()=>{const {root,dir}=await fixture();try{const cat=new Catalog(path.join(root,'app'),()=>{});const result=await cat.importFiles([path.join(dir,'DSC001.JPG')]);assert.equal(result.report.completed,1);const p=cat.library.photos[0];await cat.change([p.id],{stars:5,flag:'pick',note:'Keep this one'});await cat.undo();assert.equal(cat.library.photos[0].note,'');await cat.undo(true);assert.equal(cat.library.photos[0].note,'Keep this one');const project=path.join(root,'job.LPV');await cat.saveProject(project);const doc=JSON.parse(await fs.readFile(project,'utf8'));assert.equal(doc.version,3);assert.equal(doc.library.photos[0].jpegPath,path.join(dir,'DSC001.JPG'));assert.equal((await fs.readdir(root)).some(n=>n.includes('.assets-')),false);const cache=cat.library.cacheDir;await cat.clear();await fs.rm(cache,{recursive:true,force:true});await cat.openProject(project);const restored=cat.library.photos[0];assert.equal(restored.note,'Keep this one');await fs.access(restored.jpegPath);await fs.access(photoPath(restored.previewUrl));const dest=path.join(root,'export');await fs.mkdir(dest);assert.equal((await cat.export([p.id],dest,'rename')).completed,1);assert.equal((await cat.export([p.id],dest,'skip')).skipped,1);assert.equal((await cat.export([p.id],dest,'rename')).completed,1);await fs.access(path.join(dest,'DSC001-1.JPG'))}finally{await fs.rm(root,{recursive:true,force:true})}})
test('import cancellation preserves the previous library',async()=>{const {root,dir}=await fixture();try{let cat;cat=new Catalog(path.join(root,'app'),()=>cat.cancel());cat.library={name:'previous',source:dir,photos:[],createdAt:''};const result=await cat.importFiles([path.join(dir,'DSC001.JPG')]);assert.equal(result.report.cancelled,true);assert.equal(cat.library.name,'previous')}finally{await fs.rm(root,{recursive:true,force:true})}})
test('duplicate hashes are skipped without dropping distinct same-named photos',async()=>{const {root,dir}=await fixture();try{const other=path.join(root,'other');await fs.mkdir(other);await fs.copyFile(path.join(dir,'DSC001.JPG'),path.join(other,'COPY.JPG'));await sharp({create:{width:240,height:180,channels:3,background:'#282c78'}}).jpeg().toFile(path.join(other,'DSC001.JPG'));const cat=new Catalog(path.join(root,'app'),()=>{});const r=await cat.importFiles([path.join(dir,'DSC001.JPG'),path.join(other,'COPY.JPG'),path.join(other,'DSC001.JPG')]);assert.equal(r.report.completed,2);assert.equal(r.report.skipped,1);assert.notEqual(cat.library.photos[0].jpegPath,cat.library.photos[1].jpegPath)}finally{await fs.rm(root,{recursive:true,force:true})}})


test('missing originals are reported and relinked without copying files',async()=>{const {root,dir}=await fixture();try{
 const cat=new Catalog(path.join(root,'app'),()=>{});await cat.importFiles([path.join(dir,'DSC001.JPG')]);const photo=cat.library.photos[0]
 assert.equal(photo.stars,0);assert.equal(photo.jpegPath,path.join(dir,'DSC001.JPG'))
 await cat.change([photo.id],{colorLabel:'green',review:true,viewingProfile:'neutral',stars:4})
 const project=path.join(root,'reference.LPV');await cat.saveProject(project)
 const moved=path.join(root,'moved');await fs.mkdir(moved);await fs.rename(path.join(dir,'DSC001.JPG'),path.join(moved,'DSC001.JPG'))
 await cat.openProject(project);assert.equal(cat.library.photos[0].missing,true)
 const result=await cat.relink(moved);assert.equal(result.report.completed,1);assert.equal(cat.library.photos[0].missing,false)
 assert.equal(cat.library.photos[0].colorLabel,'green');assert.equal(cat.library.photos[0].viewingProfile,'neutral')
 await cat.rerank();assert.equal(cat.library.photos[0].stars,4);assert.equal(cat.library.photos[0].ratingSource,'manual')
 await cat.saveProject(project);const saved=JSON.parse(await fs.readFile(project,'utf8'));assert.equal(saved.library.photos[0].jpegPath,path.join(moved,'DSC001.JPG'))
}finally{await fs.rm(root,{recursive:true,force:true})}})
