// Run with: pnpm exec electron tests/viewer/run.cjs
const {app,BrowserWindow}=require('electron')
const assert=require('node:assert/strict')
const path=require('node:path')
const fs=require('node:fs/promises')
const os=require('node:os')
app.whenReady().then(async()=>{
 const win=new BrowserWindow({show:false,width:1480,height:920,webPreferences:{preload:path.join(__dirname,'viewer-preload.cjs'),contextIsolation:true,backgroundThrottling:false}})
 const run=code=>win.webContents.executeJavaScript(code).catch(e=>{throw new Error(code+'\n'+e.message)})
 const wait=async code=>{for(let i=0;i<100;i++){if(await run(code))return;await new Promise(r=>setTimeout(r,50))}throw new Error('Timed out: '+code)}
 try{
  await win.loadFile(path.join(__dirname,'../../dist/index.html'))
  await wait('document.querySelectorAll(".thumb").length===24')
  assert.equal(await run('document.querySelectorAll(".app-menus").length'),0,'No duplicate HTML File/View menus')
  assert.equal(await run('document.body.textContent.includes("⌘")'),false,'Windows displays no Mac shortcut hints')
  await run(`window.viewerTest.menu('settings')`)
  await wait(`!!document.querySelector('[aria-label="App settings"]')`)
  await run(`[...document.querySelector('[aria-label="App settings"]').querySelectorAll('button')].find(b=>b.textContent.includes('Check for updates')).click()`)
  assert.equal(await run(`window.viewerTest.checks()`),1,'Settings update check is connected')
  await run(`[...document.querySelector('[aria-label="App settings"]').querySelectorAll('button')].find(b=>b.textContent==='Cancel').click()`)
  await run(`[...document.querySelectorAll('button')].find(b=>b.textContent.includes('Rename')).click()`)
  await wait(`!!document.querySelector('[aria-label="Rename photos"]')`)
  assert.equal(await run(`document.querySelector('[aria-label="Rename photos"] .primary').disabled`),true,'Rename requires preview confirmation')
  await run(`[...document.querySelector('[aria-label="Rename photos"]').querySelectorAll('button')].find(b=>b.textContent==='Cancel').click()`)
  await run('document.querySelector(".thumb").click();document.querySelector(".thumb").dispatchEvent(new MouseEvent("dblclick",{bubbles:true}))')
  await wait('document.querySelector(".measured-view img")?.naturalWidth===6000')
  await wait('document.querySelector(".measured-view img").getBoundingClientRect().width>100')
  const fits=()=>run(`(()=>{const b=document.querySelector('.measured-view').getBoundingClientRect(),i=document.querySelector('.measured-view img').getBoundingClientRect();return i.width>0&&i.height>0&&i.left>=b.left-1&&i.right<=b.right+1&&i.top>=b.top-1&&i.bottom<=b.bottom+1})()`)
  assert(await fits(),'Full resolution landscape fits viewport')
  assert.equal(await run('document.querySelectorAll(".filmstrip-section:first-of-type .film-frame").length || document.querySelector(".filmstrip-section").querySelectorAll(".film-frame").length'),4)
  assert.equal(await run('document.querySelectorAll(".filmstrip-section")[1].querySelectorAll(".film-frame").length'),24)
  const width=await run('document.querySelector(".measured-view img").getBoundingClientRect().width')
  await run(`(()=>{const el=document.querySelector('.measured-view'),r=el.getBoundingClientRect();el.dispatchEvent(new WheelEvent('wheel',{deltaY:-180,clientX:r.left+r.width/2,clientY:r.top+r.height/2,bubbles:true,cancelable:true}))})()`)
  await wait(`document.querySelector('.measured-view img').getBoundingClientRect().width>${width}`)
  await run('document.querySelector(".measured-view").dispatchEvent(new MouseEvent("dblclick",{bubbles:true}))')
  await wait(`document.querySelector('.inspect-pane small').textContent.includes('Fit')`)
  assert(await fits(),'Double click restores fit')
  await run('document.querySelectorAll(".filmstrip-section")[0].querySelectorAll("button")[1].click()')
  await wait('document.querySelector(".measured-view img")?.naturalHeight===6000')
  await wait('document.querySelector(".measured-view img").getBoundingClientRect().height>document.querySelector(".measured-view img").getBoundingClientRect().width')
  await new Promise(r=>setTimeout(r,100))
  assert(await fits(),'Portrait full resolution fits viewport: '+await run(`JSON.stringify({box:document.querySelector('.measured-view').getBoundingClientRect().toJSON(),image:document.querySelector('.measured-view img').getBoundingClientRect().toJSON()})`))
  // A portrait narrower than the viewport must still pan horizontally.
  const portrait=await run(`(()=>{const r=document.querySelector('.measured-view').getBoundingClientRect();return {x:Math.round(r.x+r.width/2),y:Math.round(r.y+r.height/2),left:document.querySelector('.measured-view img').getBoundingClientRect().left}})()`)
  win.webContents.sendInputEvent({type:'mouseDown',x:portrait.x,y:portrait.y,button:'left',clickCount:1})
  win.webContents.sendInputEvent({type:'mouseMove',x:portrait.x+60,y:portrait.y+25,button:'left'})
  await wait(`document.querySelector('.measured-view img').getBoundingClientRect().left>${portrait.left+40}`)
  win.webContents.sendInputEvent({type:'mouseUp',x:portrait.x+60,y:portrait.y+25,button:'left',clickCount:1})
  await run('document.querySelector(".measured-view").dispatchEvent(new MouseEvent("dblclick",{bubbles:true}))')
  await wait(`Math.abs(document.querySelector('.measured-view img').getBoundingClientRect().left-${portrait.left})<1`)
  win.setSize(1100,740)
  await new Promise(r=>setTimeout(r,200))
  assert(await fits(),'Image fits after window resize: '+await run(`JSON.stringify({box:document.querySelector('.measured-view').getBoundingClientRect().toJSON(),image:document.querySelector('.measured-view img').getBoundingClientRect().toJSON()})`))
  await run('document.querySelector(".preview-details summary").click();document.querySelectorAll(".filmstrip-section summary").forEach(el=>el.click())')
  await wait('!document.querySelector(".preview-details").open && [...document.querySelectorAll(".filmstrip-section")].every(el=>!el.open)')
  await run('document.body.dispatchEvent(new KeyboardEvent("keydown",{key:"p",bubbles:true}));')
  await wait('document.querySelector(".inspection-modal .photo-actions button").getAttribute("aria-pressed")==="true"')
  assert.equal(await run('document.querySelector(".preview-details").open'),false,'Ratings stay collapsed after flagging')
  await run('document.body.dispatchEvent(new KeyboardEvent("keydown",{key:"3",bubbles:true}))')
  await wait(`document.querySelector('.inspection-modal select[aria-label="Your star rating"]').value==='3'`)
  await run('document.querySelector(".preview-details summary").click();document.querySelectorAll(".filmstrip-section summary").forEach(el=>el.click())')
  await wait('document.querySelector(".preview-details").open && [...document.querySelectorAll(".filmstrip-section")].every(el=>el.open)')
  assert.equal(await run('document.querySelectorAll(".inspection-toolbar>button").length'),4,'Zoom buttons are only inside View menu')
  await fs.writeFile(path.join(os.tmpdir(),'lucci-viewer-qa.png'),(await win.webContents.capturePage()).toPNG())
  await run('document.body.dispatchEvent(new KeyboardEvent("keydown",{key:"Escape",bubbles:true}))')
  await wait('!document.querySelector(".inspection-modal")')
  await run('document.querySelector("input[type=checkbox]").click()')
  await wait('document.querySelectorAll(".thumb").length===21')
  await run('document.querySelector(".thumb").click();document.querySelector(".thumb").dispatchEvent(new MouseEvent("dblclick",{bubbles:true}))')
  await wait('!!document.querySelector(".inspection-modal")')
  await run('document.body.dispatchEvent(new KeyboardEvent("keydown",{key:"ArrowRight",bubbles:true}))')
  await wait('document.querySelector(".inspect-label b").textContent==="Frame 02"')
  console.log('PASS: RAW fit, portrait fit, resize, wheel zoom, reset, burst previews, collection filmstrip, grouped navigation. Screenshot: '+path.join(os.tmpdir(),'lucci-viewer-qa.png'))
 }catch(e){console.error(e);process.exitCode=1}finally{win.destroy();app.exit(process.exitCode||0)}
})
