import {useEffect,useMemo,useRef,useState} from 'react'
import {Bookmark,Check,Download,FileInput,FolderOpen,Save,Search,Star,Undo2,Redo2,X,ScanSearch,Columns2,RefreshCw} from 'lucide-react'
import type {Photo,Library,ImportProgress,Report,Patch} from './types'
import Inspect,{Filmstrip} from './Inspect'
import {Metadata,PhotoActions,Profile,colors} from './PhotoControls'
import RenameDialog from './RenameDialog'
const api=window.photoAPI
const shortcut=(key:string,shift=false)=>api.platform==='darwin'?`${shift?'⇧':''}⌘${key}`:`Ctrl+${shift?'Shift+':''}${key}`
function Stars({value,change}:{value:number;change:(n:number)=>void}){return <span className="stars">{[1,2,3,4,5].map(n=><button key={n} title={`${n} stars`} aria-label={`${n} stars`} onClick={e=>{e.stopPropagation();change(n)}}><Star size={14} className={n<=value?'filled':''}/></button>)}</span>}
export default function App(){
 const savedUi=useMemo<{gridSize?:number;groupBursts?:boolean}>(()=>{try{return JSON.parse(localStorage.getItem('lpv.settings')||'{}')}catch{return {}}},[])
 const [lib,setLib]=useState<Library|null>(null),[active,setActive]=useState<string>(''),[selected,setSelected]=useState<string[]>([]),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[sort,setSort]=useState('score'),[grouped,setGrouped]=useState(!!savedUi.groupBursts),[size,setSize]=useState(Number(savedUi.gridSize)>=150&&Number(savedUi.gridSize)<=320?Number(savedUi.gridSize):200)
 const [minStars,setMinStars]=useState(0),[fileType,setFileType]=useState('all'),[colorFilter,setColorFilter]=useState('all'),[cameraFilter,setCameraFilter]=useState('all'),[fromDate,setFromDate]=useState(''),[toDate,setToDate]=useState(''),[missingOpen,setMissingOpen]=useState(false)
 const [viewingProfile,setViewingProfile]=useState(()=>{try{return localStorage.getItem('lpv.rawViewingProfile')||'neutral'}catch{return 'neutral'}})
 function changeViewingProfile(patch:Patch){if(!patch.viewingProfile)return;setViewingProfile(patch.viewingProfile);try{localStorage.setItem('lpv.rawViewingProfile',patch.viewingProfile)}catch{/* Session preference remains available if storage is unavailable. */}}
 const [renameOpen,setRenameOpen]=useState(false)
 const [zoomRevision,setZoomRevision]=useState(0)
 function applyZoom(value:boolean){setZoom(value);setZoomRevision(n=>n+1)}
 const [busy,setBusy]=useState(false),[progress,setProgress]=useState<ImportProgress|null>(null),[report,setReport]=useState<Report|null>(null),[error,setError]=useState(''),[view,setView]=useState<string[]>([]),[zoom,setZoom]=useState(false),[best,setBest]=useState(false),[n,setN]=useState(200),[variety,setVariety]=useState(.7),[suggestions,setSuggestions]=useState<string[]>([]),[exportOpen,setExportOpen]=useState(false),[conflict,setConflict]=useState<'rename'|'skip'>('rename'),[keys,setKeys]=useState(false),[settingsOpen,setSettingsOpen]=useState(false),[autoUpdates,setAutoUpdates]=useState(true),[hardwareAcceleration,setHardwareAcceleration]=useState(true),[photoEditor,setPhotoEditor]=useState(''),[settingsSize,setSettingsSize]=useState(size),[settingsGrouped,setSettingsGrouped]=useState(grouped),[context,setContext]=useState<{id:string;x:number;y:number}|null>(null)
 useEffect(()=>{document.body.classList.toggle('mac',api.platform==='darwin');api.loadLibrary().then(next=>{setLib(next);setMissingOpen(!!next?.photos.some(p=>p.missing))}).catch(e=>setError(e.message));return api.onImportProgress(setProgress)},[])
 const orderedPhotos=useMemo(()=>{let p=(lib?.photos||[]).filter(p=>(filter==='all'||filter==='pick'&&p.flag==='pick'||filter==='reject'&&p.flag==='reject'||filter==='bookmark'&&p.bookmarked||filter==='top'&&p.stars>=4||filter==='unrated'&&p.stars===0||filter==='unflagged'&&(!p.flag||p.flag==='none')||filter==='review'&&p.review||filter==='missing'&&p.missing)&&p.stars>=minStars&&(fileType==='all'||fileType==='raw'&&!!p.rawPath||fileType==='jpeg'&&!p.rawPath&&!!p.jpegPath||fileType==='pair'&&!!p.rawPath&&!!p.jpegPath)&&(colorFilter==='all'||(p.colorLabel||'none')===colorFilter)&&(cameraFilter==='all'||p.camera===cameraFilter)&&(!fromDate||!!p.capturedAt&&p.capturedAt>=new Date(fromDate+'T00:00:00').toISOString())&&(!toDate||!!p.capturedAt&&p.capturedAt<=new Date(toDate+'T23:59:59.999').toISOString())&&(!query||(p.stem+' '+p.note).toLowerCase().includes(query.toLowerCase())))
   p=[...p].sort((a,b)=>sort==='score'?b.score-a.score:sort==='stars'?b.stars-a.stars:(a.capturedAt||a.stem).localeCompare(b.capturedAt||b.stem));return p},[lib,filter,query,sort,minStars,fileType,colorFilter,cameraFilter,fromDate,toDate])
 const photos=useMemo(()=>{if(!grouped)return orderedPhotos;const seen=new Set<string>();return orderedPhotos.filter(p=>{const id=p.burstId||p.id;if(seen.has(id))return false;seen.add(id);return true})},[orderedPhotos,grouped])
 const viewing=lib?.photos.find(p=>p.id===view[0])
 const burst=useMemo(()=>viewing?.burstId?(lib?.photos||[]).filter(p=>p.burstId===viewing.burstId).sort((a,b)=>(a.capturedAt||a.stem).localeCompare(b.capturedAt||b.stem)):[],[lib,viewing?.burstId])
 function viewPhoto(p:Photo){setActive(p.id);setSelected([p.id]);setView([p.id])}
 const current=lib?.photos.find(p=>p.id===active),exportIds=lib?.photos.filter(p=>(p.bookmarked||p.flag==='pick')&&p.flag!=='reject').map(p=>p.id)||[]
 async function operation(fn:()=>Promise<any>){setBusy(true);setProgress(null);setError('');try{const result=await fn();if(result?.report){setReport(result.report);setLib(result.library);setMissingOpen(!!result.library?.photos.some((p:Photo)=>p.missing))}else if(result?.title){setReport(result);setLib(await api.loadLibrary())}return result}catch(e){setError((e as Error).message)}finally{setBusy(false);setProgress(null)}}
 async function change(patch:Patch,ids=view.length===1?view:selected.length?selected:active?[active]:[]){try{setLib(await api.updatePhotos(ids,patch))}catch(e){setError((e as Error).message)}}
 async function history(redo=false){try{setLib(await api.undo(redo))}catch(e){setError((e as Error).message)}}
 function choose(p:Photo,e?:{shiftKey:boolean;metaKey:boolean;ctrlKey:boolean}){if(e?.shiftKey&&active){const a=photos.findIndex(p=>p.id===active),b=photos.findIndex(x=>x.id===p.id);setSelected(photos.slice(Math.max(0,Math.min(a,b)),Math.max(a,b)+1).map(p=>p.id))}else if(e?.metaKey||e?.ctrlKey)setSelected(prev=>prev.includes(p.id)?prev.filter(id=>id!==p.id):[...prev,p.id]);else setSelected([p.id]);setActive(p.id)}
 function navigate(delta:number){const sequence=view.length?orderedPhotos:photos,index=sequence.findIndex(p=>p.id===active),p=sequence[Math.max(0,Math.min(sequence.length-1,index+delta))];if(p){choose(p);if(view.length===1)setView([p.id])}}
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{
   const target=e.target instanceof HTMLElement?e.target:null,editing=!!target?.closest('textarea,input:not([type=checkbox]):not([type=range]),[contenteditable=true],select')
   if(e.key==='Escape'&&context){e.preventDefault();setContext(null);return}
   if(e.key==='Escape'&&renameOpen)return
   if(e.key==='Escape'){e.preventDefault();if(best||keys||exportOpen||report||missingOpen||settingsOpen){setBest(false);setKeys(false);setExportOpen(false);setReport(null);setMissingOpen(false);setSettingsOpen(false)}else{setView([]);target?.blur()}return}
   if(editing||renameOpen||busy||best||keys||exportOpen||report||missingOpen||settingsOpen)return
   const k=e.key.toLowerCase(),mod=api.platform==='darwin'?e.metaKey:e.ctrlKey
   if(mod){if(k==='z'){e.preventDefault();void history(e.shiftKey)}else if(k==='a'){e.preventDefault();setSelected((lib?.photos||[]).map(p=>p.id))}else if(k==='s'){e.preventDefault();void operation(()=>api.saveGrid())}else if(k==='o'){e.preventDefault();void open()}else if(k==='e'&&exportIds.length){e.preventDefault();setExportOpen(true)}return}
   if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();navigate(e.key==='ArrowRight'?1:-1);return}
   if(/^[0-5]$/.test(k)){e.preventDefault();void change({stars:+k})}
   if(['p','x','u','b','r'].includes(k)&&current){e.preventDefault();void change(k==='p'?{flag:'pick'}:k==='x'?{flag:'reject'}:k==='u'?{flag:'none'}:k==='b'?{bookmarked:!current.bookmarked}:{review:!current.review})}
   if((e.key==='Enter'&&!target?.closest('button')||e.key==='F3')&&active){e.preventDefault();setView(view.length?[]:[active]);applyZoom(false)}
   if(k==='c'&&selected.length===2){e.preventDefault();setView(selected);applyZoom(false)}
   if(k==='z'&&view.length){e.preventDefault();applyZoom(!zoom)}
   if(k==='?'){e.preventDefault();setKeys(true)}
 };window.addEventListener('keydown',fn,true);return()=>window.removeEventListener('keydown',fn,true)})
 async function open(){const next=await operation(()=>api.openGrid());if(next?.photos){setLib(next);setSelected([]);setActive('');setMissingOpen(next.photos.some((p:Photo)=>p.missing))}}
 function startRename(){if(lib&&!busy)setRenameOpen(true)}
 useEffect(()=>api.onMenuAction?.(action=>{
  if(busy||renameOpen)return
  const editing=document.activeElement?.matches('input,textarea,[contenteditable=true]')
  if((action==='undo'||action==='redo')&&editing){document.execCommand(action);return}
  if(best||keys||exportOpen||report||missingOpen||settingsOpen)return
  if(action==='open')void open()
  else if(action==='new')void newCatalog()
  else if(action==='select')setSelected((lib?.photos||[]).map(p=>p.id))
  else if(action==='deselect')setSelected([])
  else if(action==='save'&&lib)void operation(()=>api.saveGrid())
  else if(action==='import')void operation(()=>api.importCard())
  else if(action==='import-folder')void operation(()=>api.importFolder())
  else if(action==='export'&&exportIds.length)setExportOpen(true)
  else if(action==='rename')startRename()
  else if(action==='undo'||action==='redo')void history(action==='redo')
  else if(action==='preview'&&active){setView(view.length?[]:[active]);applyZoom(false)}
  else if(action==='fit')applyZoom(false)
  else if(action==='actual')applyZoom(true)
  else if(action==='shortcuts')setKeys(true)
  else if(action==='settings')void openSettings()
 }))
 async function openSettings(){try{const settings=await api.settings();setAutoUpdates(settings.autoUpdates);setHardwareAcceleration(settings.hardwareAcceleration);setPhotoEditor(settings.photoEditor||'');setSettingsSize(size);setSettingsGrouped(grouped);setSettingsOpen(true)}catch(e){setError((e as Error).message)}}
 async function choosePhotoEditor(){try{const settings=await api.choosePhotoEditor();setPhotoEditor(settings.photoEditor||'')}catch(e){setError((e as Error).message)}}
 async function openInEditor(id:string,kind:'raw'|'jpeg'){setContext(null);try{await api.openInPhotoEditor(id,kind)}catch(e){setError((e as Error).message)}}
 async function saveSettings(){try{await api.saveSettings({autoUpdates,hardwareAcceleration});setSize(settingsSize);setGrouped(settingsGrouped);localStorage.setItem('lpv.settings',JSON.stringify({gridSize:settingsSize,groupBursts:settingsGrouped}));setSettingsOpen(false)}catch(e){setError((e as Error).message)}}
 async function newCatalog(){try{const next=await api.newGrid();if(next){setLib(next);setSelected([]);setActive('');setView([]);setMissingOpen(false)}}catch(e){setError((e as Error).message)}}
 const resetFilters=()=>{setFilter('all');setQuery('');setMinStars(0);setFileType('all');setColorFilter('all');setCameraFilter('all');setFromDate('');setToDate('')}
 const filters=<div className="advanced-filters"><label>Rating<select aria-label="Minimum stars" value={minStars} onChange={e=>setMinStars(+e.target.value)}>{[0,1,2,3,4,5].map(n=><option key={n} value={n}>{n===0?'Any rating':n+' ★ and up'}</option>)}</select></label><label>Files<select value={fileType} onChange={e=>setFileType(e.target.value)}><option value="all">All formats</option><option value="raw">RAW</option><option value="jpeg">JPEG only</option><option value="pair">RAW + JPEG</option></select></label><label>Label<select value={colorFilter} onChange={e=>setColorFilter(e.target.value)}><option value="all">All colors</option>{colors.map(c=><option key={c}>{c}</option>)}</select></label><label>Camera<select value={cameraFilter} onChange={e=>setCameraFilter(e.target.value)}><option value="all">All cameras</option>{Array.from(new Set(lib?.photos.map(p=>p.camera).filter(Boolean))).map(c=><option key={c}>{c}</option>)}</select></label><label>From<input type="date" value={fromDate} onChange={e=>setFromDate(e.target.value)}/></label><label>To<input type="date" value={toDate} onChange={e=>setToDate(e.target.value)}/></label><button onClick={resetFilters}>Reset filters</button></div>
 const projectActions=<><button disabled={busy} onClick={open}>Open <kbd>{shortcut('O')}</kbd></button><button disabled={!lib||busy} onClick={()=>operation(()=>api.saveGrid())}>Save LPV <kbd>{shortcut('S')}</kbd></button><button disabled={!exportIds.length||busy} onClick={()=>setExportOpen(true)}>Export {exportIds.length} <kbd>{shortcut('E')}</kbd></button><button disabled={!lib||busy} onClick={startRename}>Rename <kbd>F2</kbd></button></>
 const logo=<div className="brand"><img className="app-logo" src="./app-icon.svg" alt=""/><span>Lucci's Photo Select</span></div>
 return <div className="lpv-app"><header className="drag-region">{logo}<div className="search"><Search size={16}/><input placeholder="Search filenames and notes" value={query} onChange={e=>setQuery(e.target.value)}/></div>{projectActions}<button className="ghost" disabled={busy} onClick={()=>operation(()=>api.importCard())}><FileInput size={16}/>Select files</button><button className="ghost" disabled={busy} onClick={()=>operation(()=>api.importFolder())}><FolderOpen size={16}/>Select folder</button></header>
 {!lib?<div className="lpv-welcome"><img src="./app-icon.svg" width={110}/><h1>Find the frames worth keeping.</h1><p>Import photos, compare the best moments, and save a project linked to your originals.</p><div><button className="primary" onClick={()=>operation(()=>api.importCard())}>Select files</button><button className="ghost" onClick={()=>operation(()=>api.importFolder())}>Select folder</button><button className="ghost" onClick={open}>Open .LPV</button></div></div>:<>
 <aside><div className="section-label">WORKING LIBRARY</div><div className="source"><b>{lib.name}</b><small>{lib.projectPath||lib.source}</small><small>{lib.photos.length} photos · LPV stores file locations</small></div><div className="section-label">FILTERS</div>{[['all','All photos'],['top','Four stars +'],['unrated','Unrated'],['unflagged','Unflagged'],['pick','Picks'],['bookmark','Bookmarks'],['reject','Rejected'],['review','Needs review'],['missing','Missing files']].map(([id,label])=><button key={id} className={filter===id?'active':''} onClick={()=>setFilter(id)}>{label}</button>)}<button disabled={busy} onClick={()=>operation(()=>api.relink())}><ScanSearch size={16}/>Locate missing files</button><button disabled={busy} onClick={()=>operation(()=>api.rerank())}><RefreshCw size={16}/>Reanalyze</button><button onClick={()=>setKeys(true)}>Keyboard shortcuts <kbd>?</kbd></button><button disabled={busy} onClick={async()=>{await api.clearLibrary();setLib(null);setSelected([]);setActive('');setView([])}}>Close library</button></aside>
 <main><div className="collection-heading"><div><small>COLLECTION</small><h1>{lib.name}</h1></div><button disabled={!active} onClick={()=>{setView([active]);applyZoom(false)}}>Preview · F3</button></div><div className="lpv-toolbar"><span>{photos.length} shown · {selected.length} selected</span><button disabled={busy} onClick={()=>history()} title="Undo"><Undo2 size={16}/><kbd>{shortcut('Z')}</kbd></button><button disabled={busy} onClick={()=>history(true)} title="Redo"><Redo2 size={16}/><kbd>{shortcut('Z',true)}</kbd></button><button onClick={()=>{setBest(true);setSuggestions([])}}>Select best N</button><button disabled={selected.length!==2} onClick={()=>{setView(selected);applyZoom(false)}}><Columns2 size={16}/>Compare two <kbd>C</kbd></button><label><input type="checkbox" checked={grouped} onChange={e=>setGrouped(e.target.checked)}/>Group bursts</label><select value={sort} onChange={e=>setSort(e.target.value)}><option value="score">Technical score</option><option value="stars">Stars</option><option value="time">Capture order</option></select><input aria-label="Grid size" type="range" min={150} max={320} value={size} onChange={e=>setSize(+e.target.value)}/></div>
 {filters}
 {!!selected.length&&<div className="bulk-bar"><PhotoActions photo={current} disabled={busy} change={patch=>void change(patch)}/><button onClick={()=>setSelected([])}>Clear selection</button></div>}
 <div className="grid" style={{gridTemplateColumns:`repeat(auto-fill,minmax(${size}px,1fr))`}}>{photos.map(p=><article key={p.id} className={'thumb '+(selected.includes(p.id)?'selected ':'')+(p.flag==='reject'?'is-rejected':'')} onClick={e=>choose(p,e)} onContextMenu={e=>{e.preventDefault();setActive(p.id);if(!selected.includes(p.id))setSelected([p.id]);setContext({id:p.id,x:e.clientX,y:e.clientY})}} onDoubleClick={()=>{setView([p.id]);applyZoom(false)}}><img alt={p.stem} loading="lazy" src={p.previewUrl}/><span className={'flag-badge '+p.flag}>{p.flag==='pick'?<Check size={14}/>:p.flag==='reject'?<X size={14}/>:null}</span><div className="thumb-meta"><Stars value={p.stars} change={n=>change({stars:n},[p.id])}/><span>{p.bookmarked?'◆ ':''}{p.review?'? ':''}{p.missing?'Missing · ':''}{p.stem}</span>{p.colorLabel&&p.colorLabel!=='none'&&<i className="color-marker" style={{background:p.colorLabel}} title={p.colorLabel}/>}</div>{grouped&&<button className="burst-count" onClick={e=>{e.stopPropagation();const group=lib.photos.filter(x=>(x.burstId||x.id)===(p.burstId||p.id));setGrouped(false);setSelected(group.map(p=>p.id));setActive(p.id)}}>{lib.photos.filter(x=>(x.burstId||x.id)===(p.burstId||p.id)).length} frames</button>}</article>)}</div></main>
 {context&&(()=>{const photo=lib?.photos.find(p=>p.id===context.id);if(!photo)return null;const apply=(patch:Patch)=>{setContext(null);void change(patch,[photo.id])};return <><button className="context-dismiss" aria-label="Close photo menu" onClick={()=>setContext(null)}/><div className="photo-context" role="menu" style={{left:Math.max(8,Math.min(context.x,window.innerWidth-235)),top:Math.max(8,Math.min(context.y,window.innerHeight-390))}}><b>{photo.stem}</b><button disabled={!photo.rawPath||photo.missingRaw} onClick={()=>void openInEditor(photo.id,'raw')}>Open RAW in Photo Editor</button><button disabled={!photo.jpegPath||photo.missingJpeg} onClick={()=>void openInEditor(photo.id,'jpeg')}>Open JPEG in Photo Editor</button><button onClick={()=>{setContext(null);viewPhoto(photo)}}>Open Preview</button><hr/><button onClick={()=>apply({flag:'pick'})}>✓ Pick</button><button onClick={()=>apply({flag:'reject'})}>× Reject</button><button onClick={()=>apply({flag:'none'})}>Clear flag</button><button onClick={()=>apply({bookmarked:!photo.bookmarked})}>{photo.bookmarked?'Remove bookmark':'Bookmark'}</button><button onClick={()=>apply({review:!photo.review})}>{photo.review?'Clear review marker':'Mark for review'}</button><hr/><span>Rating</span><div className="context-stars">{[0,1,2,3,4,5].map(stars=><button key={stars} onClick={()=>apply({stars})}>{stars||'—'}</button>)}</div></div></>})()}
 {current&&<section className="inspector"><div className="inspector-head">PHOTO DETAILS<button onClick={()=>setActive('')}><X size={16}/></button></div><img className="hero" alt={current.stem} src={current.previewUrl} onDoubleClick={()=>setView([current.id])}/><h2>{current.stem}</h2><div className="detail-pad"><Stars value={current.stars} change={n=>change({stars:n},[current.id])}/><Metadata photo={current}/><Profile photo={{...current,viewingProfile}} change={changeViewingProfile}/><p>Technical score: {current.score.toFixed(1)} / 5 · {current.review?'Needs review':'Subject check'}</p><small>Your stars are separate from automatic scores. Older automatic stars are preserved; set 0 to clear them.</small>{[['Regional / eye focus',current.sharpness],['Exposure',current.exposure],['Low noise',5-current.noise],['Face crop safety',current.framing]].map(([label,value])=><div className="metric" key={String(label)}><span>{label}</span><b>{Number(value)<0?'Review':Number(value).toFixed(1)}</b></div>)}<small>{current.faceCount||0} faces detected · {current.camera||'Camera unknown'}{current.iso?` · ISO ${current.iso}`:''}</small><ul>{(current.ratingNotes||['Legacy rating — reanalyze for updated measurements.']).map(n=><li key={n}>{n}</li>)}</ul><label>Notes<textarea key={current.id} defaultValue={current.note} placeholder="Notes for this photo" onBlur={e=>{if(e.target.value!==current.note)void change({note:e.target.value},[current.id])}}/></label><p>{current.rawPath?'RAW':''}{current.rawPath&&current.jpegPath?' + ':''}{current.jpegPath?'JPEG':''}</p></div></section>}
 </>}
 {!!view.length&&<div className="inspection-modal" role="dialog" aria-label="Photo preview"><div className="inspection-toolbar"><button onClick={()=>setView([])}>← Thumbnails <kbd>F3</kbd></button><button onClick={()=>navigate(-1)} disabled={view.length!==1||orderedPhotos.findIndex(p=>p.id===active)<=0}>Previous <kbd>←</kbd></button><button onClick={()=>navigate(1)} disabled={view.length!==1||orderedPhotos.findIndex(p=>p.id===active)>=orderedPhotos.length-1}>Next <kbd>→</kbd></button><span>{view.length===2?'Compare photos':'Photo preview'} · Scroll to zoom</span><button onClick={()=>setView([])}>Close <kbd>Esc</kbd></button></div><div className="fullscreen-actions">{projectActions}<button disabled={busy} onClick={()=>history()}>Undo <kbd>{shortcut('Z')}</kbd></button><button disabled={busy} onClick={()=>history(true)}>Redo <kbd>{shortcut('Z',true)}</kbd></button><button disabled={busy} onClick={()=>operation(()=>api.relink())}>Locate missing files</button><button disabled={busy} onClick={()=>operation(()=>api.rerank())}>Reanalyze</button><button onClick={()=>{setBest(true);setSuggestions([])}}>Select best N</button><button disabled={selected.length!==2} onClick={()=>setView(selected)}>Compare <kbd>C</kbd></button></div><PhotoActions photo={current} disabled={busy} change={patch=>void change(patch)}/><div className="preview-body"><div className="inspection-panels">{view.map(id=>lib?.photos.find(p=>p.id===id)).filter(Boolean).map(p=><Inspect key={p!.id} photo={{...p!,viewingProfile:p!.rawPath?viewingProfile:'neutral'}} zoom={zoom} zoomRevision={zoomRevision}/>)}</div>{current&&<details className="preview-details" open><summary>Ratings & photo info</summary><h2>{current.stem}</h2><p>Your rating: {current.stars} ★</p><p>Technical score {current.score.toFixed(1)} / 5</p>{[['Subject / eye focus',current.sharpness],['Exposure',current.exposure],['Low noise',5-current.noise]].map(([name,value])=><div className="metric" key={String(name)}><span>{name}</span><b>{Number(value).toFixed(1)} / 5</b></div>)}<small>{current.review?'Needs review · subject focus uncertain':'Technical assessment, not an aesthetic rating'}</small><ul>{current.ratingNotes?.map(n=><li key={n}>{n}</li>)}</ul><Metadata photo={current}/><Profile photo={{...current,viewingProfile}} change={changeViewingProfile}/><label>Notes<textarea key={current.id} defaultValue={current.note} onBlur={e=>void change({note:e.target.value},[current.id])}/></label></details>}</div>{view.length===1&&burst.length>1&&<Filmstrip photos={burst} active={active} label="Current burst" onChoose={viewPhoto}/>}<Filmstrip photos={orderedPhotos} active={active} label="Collection · current filter and order" onChoose={viewPhoto}/></div>}
 {renameOpen&&<RenameDialog ids={selected.length?selected:active?[active]:[]} allIds={orderedPhotos.map(p=>p.id)} close={()=>setRenameOpen(false)} done={result=>{setLib(result.library);setReport(result.report);setRenameOpen(false)}}/>}
 {settingsOpen&&<div className="modal"><div className="lpv-dialog" role="dialog" aria-label="App settings"><h2>Settings</h2><label><span>Photo editor</span><button onClick={()=>void choosePhotoEditor()}>{photoEditor?'Change editor…':'Choose .exe or .app…'}</button></label><p>{photoEditor||'No photo editor selected. Right-click a catalog photo after choosing one.'}</p><label><span>Check for updates automatically</span><input type="checkbox" checked={autoUpdates} onChange={e=>setAutoUpdates(e.target.checked)}/></label><label><span>Use hardware acceleration for display</span><input type="checkbox" checked={hardwareAcceleration} onChange={e=>setHardwareAcceleration(e.target.checked)}/></label><p>Hardware acceleration can improve interface and image display performance. Restart the app after changing it.</p><label><span>Default grid thumbnail size</span><input type="range" min={150} max={320} value={settingsSize} onChange={e=>setSettingsSize(+e.target.value)}/><b>{settingsSize}px</b></label><label><span>Group bursts by default</span><input type="checkbox" checked={settingsGrouped} onChange={e=>setSettingsGrouped(e.target.checked)}/></label><button onClick={()=>void api.checkUpdates()}>Check for updates now</button><button className="primary" onClick={()=>void saveSettings()}>Save settings</button><button onClick={()=>setSettingsOpen(false)}>Cancel</button></div></div>}
 {missingOpen&&<div className="modal"><div className="lpv-dialog"><h2>Original files are missing</h2><p>{lib?.photos.filter(p=>p.missing).length} photos have unavailable originals. Use Locate missing files to choose their current folder. LPV projects store locations, not copies of photos.</p><button onClick={()=>{setMissingOpen(false);void operation(()=>api.relink())}}>Locate missing files</button><button onClick={()=>setMissingOpen(false)}>Continue reviewing</button></div></div>}
 {best&&<div className="modal"><div className="lpv-dialog"><h2>Select the best photos</h2><label>How many?<input type="number" min={1} max={lib?.photos.length||1} value={n} onChange={e=>setN(Math.max(1,+e.target.value))}/></label><label>Variety<input type="range" min={0} max={1} step={.1} value={variety} onChange={e=>setVariety(+e.target.value)}/></label><p>{variety<.3?'Favor the highest quality scores.':'Reduce repeated bursts and visually similar frames.'} Rejected photos are excluded.</p><button onClick={async()=>{const ids=await operation(()=>api.suggest(n,variety));if(ids)setSuggestions(ids)}}>Preview suggestion</button>{!!suggestions.length&&<><p>{suggestions.length} photos suggested. Review them in the grid before marking picks.</p><div className="suggest-strip">{suggestions.slice(0,10).map(id=><img key={id} src={lib?.photos.find(p=>p.id===id)?.previewUrl}/>)}</div><button className="primary" onClick={()=>{setSelected(suggestions);setActive(suggestions[0]);setGrouped(false);resetFilters();setBest(false);setView([])}}>Review selected photos</button></>}<button onClick={()=>setBest(false)}>Cancel</button></div></div>}
 {exportOpen&&<div className="modal"><div className="lpv-dialog"><h2>Export {exportIds.length} photos</h2><p>Copies RAW and JPEG originals for picks and bookmarks. Rejected photos are excluded.</p><label>Existing filenames<select value={conflict} onChange={e=>setConflict(e.target.value as 'rename'|'skip')}><option value="rename">Rename incoming pairs</option><option value="skip">Skip conflicting pairs</option></select></label><button className="primary" onClick={()=>{setExportOpen(false);void operation(()=>api.exportPhotos(exportIds,conflict))}}>Choose destination</button><button onClick={()=>setExportOpen(false)}>Cancel</button></div></div>}
 {busy&&<div className="modal"><div className="lpv-dialog"><h2>{progress?.phase||'Preparing…'}</h2><p>{progress?.file}</p><progress max={progress?.total||1} value={progress?.current||0}/><p>{progress?.current||0} / {progress?.total||0}</p><button onClick={()=>api.cancel()}>Cancel operation</button></div></div>}
 {report&&<div className="modal"><div className="lpv-dialog"><h2>{report.title}{report.cancelled?' cancelled':' complete'}</h2><p>{report.completed} completed · {report.skipped} skipped · {report.errors.length} issues</p>{report.folder&&<p>{report.folder}</p>}<ul>{report.errors.map((e,i)=><li key={i}>{e}</li>)}</ul><button onClick={()=>setReport(null)}>Done</button></div></div>}
 {error&&<div className="error-toast" role="alert">{error}<button onClick={()=>setError('')}>Dismiss</button></div>}
 {keys&&<div className="modal"><div className="lpv-dialog"><h2>Quick culling</h2><p>← / → navigate · Enter / F3 preview · C compare two</p><p>P pick · X reject · U clear flag · B bookmark · R review marker</p><p>Z fit / 100% in preview · 0–5 set your stars · {shortcut('A')} select all catalog photos</p><p>{shortcut('Z')} undo · {shortcut('Z',true)} redo</p><p>Shift-click selects a range. {api.platform==='darwin'?'⌘':'Ctrl'}-click toggles individual photos.</p><button onClick={()=>setKeys(false)}>Close</button></div></div>}
 </div>
}
