import { useEffect,useMemo,useState } from 'react'
import { Bookmark,Check,ChevronDown,Download,Expand,FileInput,FolderOpen,Grid3X3,Info,Keyboard,Save,Search,SlidersHorizontal,Star,Trash2,X } from 'lucide-react'
import type { ImportProgress,Library,Photo } from './types'

const StarRating=({value,onChange,small=false}:{value:number,onChange?:(n:number)=>void,small?:boolean})=><div className={'stars '+(small?'small':'')} onClick={e=>e.stopPropagation()}>{[1,2,3,4,5].map(n=><Star key={n} className={n<=value?'filled':''} onClick={()=>onChange?.(n)}/>)}</div>
const AppLogo=()=> <img className="app-logo" src="./app-icon.svg" alt="Lucci's Photo Select"/>

export default function App(){
 const [lib,setLib]=useState<Library|null>(null),[selected,setSelected]=useState<Photo|null>(null),[progress,setProgress]=useState<ImportProgress|null>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState<'all'|'bookmarked'|'top'|'picks'|'rejected'>('all'),[sort,setSort]=useState<'score'|'name'>('score'),[importing,setImporting]=useState(false),[loupe,setLoupe]=useState(false),[showKeys,setShowKeys]=useState(false),[thumbSize,setThumbSize]=useState(190)
 useEffect(()=>{document.body.classList.toggle('mac',window.photoAPI.platform==='darwin');window.photoAPI.loadLibrary().then(setLib);return window.photoAPI.onImportProgress(setProgress)},[])
 const photos=useMemo(()=>{let p=lib?.photos||[];if(filter==='bookmarked')p=p.filter(x=>x.bookmarked);if(filter==='top')p=p.filter(x=>x.stars>=4);if(filter==='picks')p=p.filter(x=>x.flag==='pick');if(filter==='rejected')p=p.filter(x=>x.flag==='reject');if(query)p=p.filter(x=>x.stem.toLowerCase().includes(query.toLowerCase())||x.note.toLowerCase().includes(query.toLowerCase()));return [...p].sort((a,b)=>sort==='score'?b.score-a.score:a.stem.localeCompare(b.stem))},[lib,filter,query,sort])
 const update=async(p:Photo,patch:Partial<Photo>)=>{Object.assign(p,patch);setLib(lib?{...lib,photos:[...lib.photos]}:null);setSelected(selected?.id===p.id?{...p}:selected);await window.photoAPI.updatePhoto(p.id,patch)}
 const doImport=async()=>{setImporting(true);setProgress({phase:'Preparing',current:0,total:1});try{const next=await window.photoAPI.importCard();if(next){setLib(next);setSelected(null)}}finally{setImporting(false);setProgress(null)}}
 const navigate=(delta:number)=>{if(!photos.length)return;const i=selected?photos.findIndex(p=>p.id===selected.id):-1;setSelected(photos[Math.max(0,Math.min(photos.length-1,i+delta))])}
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.matches('input,textarea,select'))return;if(e.key==='ArrowRight'){navigate(1);e.preventDefault()}if(e.key==='ArrowLeft'){navigate(-1);e.preventDefault()}if(!selected)return;if(/^[1-5]$/.test(e.key))update(selected,{stars:+e.key});if(e.key.toLowerCase()==='p')update(selected,{flag:'pick'});if(e.key.toLowerCase()==='x')update(selected,{flag:'reject'});if(e.key.toLowerCase()==='u')update(selected,{flag:'none'});if(e.key.toLowerCase()==='b')update(selected,{bookmarked:!selected.bookmarked});if(e.key==='Enter'||e.key===' '){setLoupe(true);e.preventDefault()}if(e.key==='Escape')setLoupe(false)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[selected,photos,lib])
 const exportIds=lib?.photos.filter(p=>p.bookmarked||p.flag==='pick').map(p=>p.id)||[]
 if(!lib&&!importing)return <div className="welcome drag-region"><div className="brand"><AppLogo/><span>Lucci's Photo Select</span></div><div className="welcome-card no-drag"><AppLogo/><h1>Your fastest first pass.</h1><p>Select RAW, JPEG, or paired photos from an SD card, external drive, or anywhere on your computer. Lucci's Photo Select creates fast previews and ranks every frame from one to five stars.</p><div className="welcome-actions"><button className="primary" onClick={doImport}><FileInput/> Select files</button><button className="ghost" onClick={async()=>{const next=await window.photoAPI.openGrid();if(next)setLib(next)}}><FolderOpen/> Open .LPV grid</button></div><div className="support">ARW, CR2, CR3, NEF, RAF, ORF, RW2, DNG and JPEG · RAW-only files use their embedded camera preview</div></div></div>
 return <div className="app">
  <header className="drag-region"><div className="brand compact"><AppLogo/><span>Lucci's Photo Select</span></div><div className="search no-drag"><Search/><input placeholder="Search filename or notes" value={query} onChange={e=>setQuery(e.target.value)}/></div><button className="ghost icon-button no-drag" onClick={()=>setShowKeys(true)} title="Keyboard shortcuts"><Keyboard/></button><button className="ghost icon-button no-drag" onClick={()=>window.photoAPI.saveGrid()} title="Save .LPV grid"><Save/></button><button className="ghost no-drag" onClick={doImport}><FileInput/> Select files</button><button className="primary no-drag" disabled={!exportIds.length} onClick={()=>window.photoAPI.exportPhotos(exportIds)}><Download/> Export {exportIds.length||''}</button></header>
  <aside><div className="section-label">LIBRARY</div><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}><Grid3X3/>All photos <b>{lib?.photos.length}</b></button><button className={filter==='top'?'active':''} onClick={()=>setFilter('top')}><Star/>Four stars+ <b>{lib?.photos.filter(p=>p.stars>=4).length}</b></button><button className={filter==='picks'?'active':''} onClick={()=>setFilter('picks')}><Check/>Picks <b>{lib?.photos.filter(p=>p.flag==='pick').length}</b></button><button className={filter==='bookmarked'?'active':''} onClick={()=>setFilter('bookmarked')}><Bookmark/>Bookmarked <b>{lib?.photos.filter(p=>p.bookmarked).length}</b></button><button className={filter==='rejected'?'active danger':''} onClick={()=>setFilter('rejected')}><X/>Rejected <b>{lib?.photos.filter(p=>p.flag==='reject').length}</b></button><div className="section-label">CURRENT IMPORT</div><div className="source"><div>{lib?.name}</div><small>{lib?.source}</small></div><div className="aside-bottom"><button onClick={async()=>{if(confirm('Remove this library and its local cache? Original files are not affected.')){await window.photoAPI.clearLibrary();setLib(null)}}}><Trash2/>Clear library</button></div></aside>
  <main><div className="toolbar"><div><strong>{photos.length}</strong> photos <span className="keyhint">P pick · X reject · 1–5 rate · B bookmark</span></div><div className="toolbar-actions"><span className="size-icon">A</span><input className="size-slider" type="range" min="140" max="300" value={thumbSize} onChange={e=>setThumbSize(+e.target.value)}/><SlidersHorizontal/><select value={sort} onChange={e=>setSort(e.target.value as 'score'|'name')}><option value="score">Best rated</option><option value="name">Filename</option></select><ChevronDown/></div></div><div className="grid" style={{gridTemplateColumns:`repeat(auto-fill,minmax(${thumbSize}px,1fr))`}}>{photos.map(p=><article key={p.id} className={'thumb '+(selected?.id===p.id?'selected ':'')+(p.flag==='reject'?'is-rejected':'')} onClick={()=>setSelected(p)} onDoubleClick={()=>{setSelected(p);setLoupe(true)}}><img src={p.previewUrl} loading="lazy"/><span className={'flag-badge '+(p.flag||'none')}>{p.flag==='pick'?<Check/>:p.flag==='reject'?<X/>:null}</span><button className={'bookmark '+(p.bookmarked?'on':'')} onClick={e=>{e.stopPropagation();update(p,{bookmarked:!p.bookmarked})}}><Bookmark/></button><div className="thumb-meta"><StarRating small value={p.stars} onChange={n=>update(p,{stars:n})}/><span>{p.stem}</span></div></article>)}</div></main>
  {selected&&<section className="inspector"><div className="inspector-head"><span>PHOTO DETAILS</span><button onClick={()=>setSelected(null)}><X/></button></div><div className="hero-wrap" onDoubleClick={()=>setLoupe(true)}><img className="hero" src={selected.previewUrl}/><button onClick={()=>setLoupe(true)}><Expand/></button></div><h2>{selected.stem}</h2><div className="flag-actions"><button className={selected.flag==='pick'?'pick active':'pick'} onClick={()=>update(selected,{flag:selected.flag==='pick'?'none':'pick'})}><Check/>Pick <kbd>P</kbd></button><button className={selected.flag==='reject'?'reject active':'reject'} onClick={()=>update(selected,{flag:selected.flag==='reject'?'none':'reject'})}><X/>Reject <kbd>X</kbd></button></div><div className="rating-row"><StarRating value={selected.stars} onChange={n=>update(selected,{stars:n})}/><strong>{selected.score.toFixed(1)}</strong><span>AI score</span></div><div className="scores"><Metric label="Focus" value={selected.sharpness}/><Metric label="Exposure" value={selected.exposure}/><Metric label="Low noise" value={5-selected.noise}/><Metric label="Framing" value={selected.framing}/></div><label className="bookmark-row"><input type="checkbox" checked={selected.bookmarked} onChange={e=>update(selected,{bookmarked:e.target.checked})}/><Bookmark/> Add to export selection</label><label className="notes">NOTES<textarea placeholder="Add retouching notes, client requests, or reminders…" value={selected.note} onChange={e=>update(selected,{note:e.target.value})}/></label><div className="file-info"><Info/><div><b>{selected.rawPath?'RAW + JPEG':'JPEG only'}</b><small>{selected.width} × {selected.height}</small></div></div></section>}
  {loupe&&selected&&<div className="loupe" onClick={()=>setLoupe(false)}><button className="loupe-close"><X/></button><button className="loupe-nav left" onClick={e=>{e.stopPropagation();navigate(-1)}}>‹</button><img src={selected.fullPreviewUrl||selected.previewUrl}/><button className="loupe-nav right" onClick={e=>{e.stopPropagation();navigate(1)}}>›</button><div className="loupe-caption"><b>{selected.stem}</b><span>{selected.rawPath?'RAW preview':'JPEG'}</span><StarRating value={selected.stars} onChange={n=>update(selected,{stars:n})}/></div></div>}
  {showKeys&&<div className="modal" onClick={()=>setShowKeys(false)}><div className="shortcuts" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setShowKeys(false)}><X/></button><h2>Keyboard shortcuts</h2><Shortcut keys="←  →" label="Previous / next photo"/><Shortcut keys="1–5" label="Set star rating"/><Shortcut keys="P" label="Mark as pick"/><Shortcut keys="X" label="Mark as rejected"/><Shortcut keys="U" label="Clear flag"/><Shortcut keys="B" label="Toggle bookmark"/><Shortcut keys="Enter" label="Open large preview"/><Shortcut keys="Esc" label="Close large preview"/></div></div>}
  {importing&&progress&&<div className="modal"><div className="progress-card"><div className="spinner"/><h2>{progress.phase}</h2><p>{progress.file||'Reading selected files…'}</p><div className="progress"><i style={{width:`${progress.total?progress.current/progress.total*100:0}%`}}/></div><small>{progress.current.toLocaleString()} of {progress.total.toLocaleString()}</small></div></div>}
 </div>
}
function Metric({label,value}:{label:string,value:number}){return <div className="metric"><span>{label}</span><div><i style={{width:`${Math.max(0,Math.min(100,value/5*100))}%`}}/></div><b>{value.toFixed(1)}</b></div>}
function Shortcut({keys,label}:{keys:string,label:string}){return <div className="shortcut"><kbd>{keys}</kbd><span>{label}</span></div>}
