import {useEffect,useMemo,useRef,useState} from 'react'
import {Bookmark,Check,Download,FileInput,FolderOpen,Save,Search,Star,Undo2,Redo2,X,ScanSearch,Columns2,RefreshCw} from 'lucide-react'
import type {Photo,Library,ImportProgress,Report,Patch,Inspection} from './types'
const api=window.photoAPI
function Stars({value,change}:{value:number;change:(n:number)=>void}){return <span className="stars">{[1,2,3,4,5].map(n=><button key={n} title={`${n} stars`} aria-label={`${n} stars`} onClick={e=>{e.stopPropagation();change(n)}}><Star size={14} className={n<=value?'filled':''}/></button>)}</span>}
function Inspect({photo,zoom}:{photo:Photo;zoom:boolean}){
 const [data,setData]=useState<Inspection|null>(null),[error,setError]=useState('');const box=useRef<HTMLDivElement>(null)
 useEffect(()=>{let alive=true;setData(null);setError('');api.inspect(photo.id).then(d=>{if(alive)setData(d)},e=>{if(alive)setError(String(e.message))});return()=>{alive=false}},[photo.id])
 return <section className="inspect-pane"><div className="inspect-label"><b>{photo.stem}</b><span>{data?.kind||'Loading full image…'}</span></div>{error&&<p role="alert">{error}</p>}{data?.warning&&<p>{data.warning}</p>}<div className={'inspect-canvas '+(zoom?'pixel-view':'fit-view')} ref={box} onPointerDown={e=>{if(!zoom)return;const el=box.current!,x=e.clientX,y=e.clientY,left=el.scrollLeft,top=el.scrollTop;el.setPointerCapture(e.pointerId);el.onpointermove=ev=>{el.scrollLeft=left-(ev.clientX-x);el.scrollTop=top-(ev.clientY-y)};el.onpointerup=()=>{el.onpointermove=null}}}>
 <img alt={photo.stem} src={data?.url||photo.fullPreviewUrl||photo.previewUrl} style={zoom&&data?{width:data.width/(window.devicePixelRatio||1),height:data.height/(window.devicePixelRatio||1),maxWidth:'none',maxHeight:'none'}:undefined}/></div><small>{data?`${data.width} × ${data.height} · ${zoom?'100% — drag to pan':'Fit to window'}`:'Decoding locally'}</small></section>
}
export default function App(){
 const [lib,setLib]=useState<Library|null>(null),[active,setActive]=useState<string>(''),[selected,setSelected]=useState<string[]>([]),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[sort,setSort]=useState('score'),[grouped,setGrouped]=useState(false),[size,setSize]=useState(200)
 const [busy,setBusy]=useState(false),[progress,setProgress]=useState<ImportProgress|null>(null),[report,setReport]=useState<Report|null>(null),[error,setError]=useState(''),[view,setView]=useState<string[]>([]),[zoom,setZoom]=useState(false),[best,setBest]=useState(false),[n,setN]=useState(200),[variety,setVariety]=useState(.7),[suggestions,setSuggestions]=useState<string[]>([]),[exportOpen,setExportOpen]=useState(false),[conflict,setConflict]=useState<'rename'|'skip'>('rename'),[keys,setKeys]=useState(false)
 useEffect(()=>{document.body.classList.toggle('mac',api.platform==='darwin');api.loadLibrary().then(setLib).catch(e=>setError(e.message));return api.onImportProgress(setProgress)},[])
 const photos=useMemo(()=>{let p=(lib?.photos||[]).filter(p=>(filter==='all'||filter==='pick'&&p.flag==='pick'||filter==='reject'&&p.flag==='reject'||filter==='bookmark'&&p.bookmarked||filter==='top'&&p.stars>=4)&&(!query||(p.stem+' '+p.note).toLowerCase().includes(query.toLowerCase())))
   p=[...p].sort((a,b)=>sort==='score'?b.score-a.score:sort==='stars'?b.stars-a.stars:(a.capturedAt||a.stem).localeCompare(b.capturedAt||b.stem));if(grouped){const seen=new Set<string>();p=p.filter(p=>{const id=p.burstId||p.id;if(seen.has(id))return false;seen.add(id);return true})}return p},[lib,filter,query,sort,grouped])
 const current=lib?.photos.find(p=>p.id===active),exportIds=lib?.photos.filter(p=>(p.bookmarked||p.flag==='pick')&&p.flag!=='reject').map(p=>p.id)||[]
 async function operation(fn:()=>Promise<any>){setBusy(true);setProgress(null);setError('');try{const result=await fn();if(result?.report){setReport(result.report);setLib(result.library)}else if(result?.title)setReport(result);return result}catch(e){setError((e as Error).message)}finally{setBusy(false);setProgress(null)}}
 async function change(patch:Patch,ids=selected.length?selected:active?[active]:[]){try{setLib(await api.updatePhotos(ids,patch))}catch(e){setError((e as Error).message)}}
 async function history(redo=false){try{setLib(await api.undo(redo))}catch(e){setError((e as Error).message)}}
 function choose(p:Photo,e?:{shiftKey:boolean;metaKey:boolean;ctrlKey:boolean}){if(e?.shiftKey&&active){const a=photos.findIndex(p=>p.id===active),b=photos.findIndex(x=>x.id===p.id);setSelected(photos.slice(Math.max(0,Math.min(a,b)),Math.max(a,b)+1).map(p=>p.id))}else if(e?.metaKey||e?.ctrlKey)setSelected(prev=>prev.includes(p.id)?prev.filter(id=>id!==p.id):[...prev,p.id]);else setSelected([p.id]);setActive(p.id)}
 function navigate(delta:number){const index=photos.findIndex(p=>p.id===active),p=photos[Math.max(0,Math.min(photos.length-1,index+delta))];if(p){choose(p);if(view.length===1)setView([p.id])}}
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{if((e.target as HTMLElement).matches('input,textarea,select')||busy)return;if(e.key==='Escape'){setView([]);setBest(false);setKeys(false);setExportOpen(false);return}if(e.metaKey||e.ctrlKey){if(e.key.toLowerCase()==='z'){e.preventDefault();void history(e.shiftKey)}if(e.key.toLowerCase()==='a'){e.preventDefault();setSelected(photos.map(p=>p.id))}return}if(e.key==='ArrowRight'){e.preventDefault();navigate(1)}if(e.key==='ArrowLeft'){e.preventDefault();navigate(-1)}if(/^[0-5]$/.test(e.key))void change({stars:+e.key});if(e.key.toLowerCase()==='p')void change({flag:'pick'});if(e.key.toLowerCase()==='x')void change({flag:'reject'});if(e.key.toLowerCase()==='u')void change({flag:'none'});if(e.key.toLowerCase()==='b'&&current)void change({bookmarked:!current.bookmarked});if(e.key==='Enter'&&active)setView([active]);if(e.key.toLowerCase()==='c'&&selected.length===2)setView(selected);if(e.key==='?')setKeys(true)};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[photos,active,selected,view,busy,current])
 async function open(){const next=await operation(()=>api.openGrid());if(next?.photos){setLib(next);setSelected([]);setActive('')}}
 const logo=<div className="brand"><img className="app-logo" src="./app-icon.svg" alt=""/><span>Lucci's Photo Select</span></div>
 return <div className="lpv-app"><header className="drag-region">{logo}<div className="search"><Search size={16}/><input placeholder="Search filenames and notes" value={query} onChange={e=>setQuery(e.target.value)}/></div><button className="ghost" disabled={busy} onClick={open} title="Open LPV"><FolderOpen size={16}/></button><button className="ghost" disabled={!lib||busy} onClick={()=>operation(()=>api.saveGrid())} title="Save portable LPV"><Save size={16}/></button><button className="ghost" disabled={busy} onClick={()=>operation(()=>api.importCard())}><FileInput size={16}/>Select files</button><button className="primary" disabled={!exportIds.length||busy} onClick={()=>setExportOpen(true)}><Download size={16}/>Export {exportIds.length||''}</button></header>
 {!lib?<div className="lpv-welcome"><img src="./app-icon.svg" width={110}/><h1>Find the frames worth keeping.</h1><p>Import photos, compare the best moments, and save a portable project.</p><div><button className="primary" onClick={()=>operation(()=>api.importCard())}>Select files</button><button className="ghost" onClick={open}>Open .LPV</button></div></div>:<>
 <aside>{[['all','All photos'],['top','Four stars +'],['pick','Picks'],['bookmark','Bookmarks'],['reject','Rejected']].map(([id,label])=><button key={id} className={filter===id?'active':''} onClick={()=>setFilter(id)}>{label}</button>)}<div className="section-label">PROJECT</div><div className="source"><b>{lib.name}</b><small>{lib.projectPath||'Working library — save an LPV to keep a portable copy'}</small></div><button disabled={busy} onClick={()=>operation(()=>api.relink())}><ScanSearch size={16}/>Locate missing files</button><button disabled={busy} onClick={()=>operation(()=>api.rerank())}><RefreshCw size={16}/>Reanalyze ratings</button><button onClick={()=>setKeys(true)}>Keyboard shortcuts</button><button disabled={busy} onClick={async()=>{await api.clearLibrary();setLib(null);setSelected([])}}>Close library</button></aside>
 <main><div className="lpv-toolbar"><span>{photos.length} shown · {selected.length} selected</span><button disabled={busy} onClick={()=>history()} title="Undo"><Undo2 size={16}/></button><button disabled={busy} onClick={()=>history(true)} title="Redo"><Redo2 size={16}/></button><button onClick={()=>{setBest(true);setSuggestions([])}}>Select best N</button><button disabled={selected.length!==2} onClick={()=>{setView(selected);setZoom(false)}}><Columns2 size={16}/>Compare two</button><label><input type="checkbox" checked={grouped} onChange={e=>setGrouped(e.target.checked)}/>Group bursts</label><select value={sort} onChange={e=>setSort(e.target.value)}><option value="score">Quality</option><option value="stars">Stars</option><option value="time">Capture order</option></select><input aria-label="Grid size" type="range" min={150} max={320} value={size} onChange={e=>setSize(+e.target.value)}/></div>
 {!!selected.length&&<div className="bulk-bar"><button onClick={()=>change({flag:'pick'})}>Pick</button><button onClick={()=>change({flag:'reject'})}>Reject</button><button onClick={()=>change({flag:'none'})}>Clear flag</button><button onClick={()=>change({bookmarked:true})}>Bookmark</button><Stars value={0} change={n=>change({stars:n})}/><button onClick={()=>setSelected([])}>Clear selection</button></div>}
 <div className="grid" style={{gridTemplateColumns:`repeat(auto-fill,minmax(${size}px,1fr))`}}>{photos.map(p=><article key={p.id} className={'thumb '+(selected.includes(p.id)?'selected ':'')+(p.flag==='reject'?'is-rejected':'')} onClick={e=>choose(p,e)} onDoubleClick={()=>{setView([p.id]);setZoom(false)}}><img alt={p.stem} loading="lazy" src={p.previewUrl}/><span className={'flag-badge '+p.flag}>{p.flag==='pick'?<Check size={14}/>:p.flag==='reject'?<X size={14}/>:null}</span><div className="thumb-meta"><Stars value={p.stars} change={n=>change({stars:n},[p.id])}/><span>{p.stem}</span></div>{grouped&&<button className="burst-count" onClick={e=>{e.stopPropagation();const group=lib.photos.filter(x=>(x.burstId||x.id)===(p.burstId||p.id));setGrouped(false);setSelected(group.map(p=>p.id));setActive(p.id)}}>{lib.photos.filter(x=>(x.burstId||x.id)===(p.burstId||p.id)).length} frames</button>}</article>)}</div></main>
 {current&&<section className="inspector"><div className="inspector-head">PHOTO DETAILS<button onClick={()=>setActive('')}><X size={16}/></button></div><img className="hero" alt={current.stem} src={current.previewUrl} onDoubleClick={()=>setView([current.id])}/><h2>{current.stem}</h2><div className="detail-pad"><button onClick={()=>{setView([current.id]);setZoom(true)}}>Inspect at 100%</button><Stars value={current.stars} change={n=>change({stars:n},[current.id])}/><p>Quality estimate: {current.score.toFixed(1)} / 5</p>{[['Regional / eye focus',current.sharpness],['Exposure',current.exposure],['Low noise',5-current.noise],['Face crop safety',current.framing]].map(([label,value])=><div className="metric" key={String(label)}><span>{label}</span><b>{Number(value)<0?'Review':Number(value).toFixed(1)}</b></div>)}<small>{current.faceCount||0} faces detected · {current.camera||'Camera unknown'}{current.iso?` · ISO ${current.iso}`:''}</small><ul>{(current.ratingNotes||['Legacy rating — reanalyze for updated measurements.']).map(n=><li key={n}>{n}</li>)}</ul><label>Notes<textarea key={current.id} defaultValue={current.note} placeholder="Notes for this photo" onBlur={e=>{if(e.target.value!==current.note)void change({note:e.target.value},[current.id])}}/></label><p>{current.rawPath?'RAW':''}{current.rawPath&&current.jpegPath?' + ':''}{current.jpegPath?'JPEG':''}</p></div></section>}
 </>}
 {!!view.length&&<div className="inspection-modal"><div className="inspection-toolbar"><button onClick={()=>navigate(-1)} disabled={view.length!==1}>Previous</button><button onClick={()=>navigate(1)} disabled={view.length!==1}>Next</button><button onClick={()=>setZoom(!zoom)}>{zoom?'Fit':'100%'}</button><span>{zoom?'One image pixel per display pixel · Drag to pan':'Full RAW decoding when available'}</span><button onClick={()=>setView([])}>Close ✕</button></div><div className="inspection-panels">{view.map(id=>lib?.photos.find(p=>p.id===id)).filter(Boolean).map(p=><Inspect key={p!.id} photo={p!} zoom={zoom}/>)}</div></div>}
 {best&&<div className="modal"><div className="lpv-dialog"><h2>Select the best photos</h2><label>How many?<input type="number" min={1} max={lib?.photos.length||1} value={n} onChange={e=>setN(Math.max(1,+e.target.value))}/></label><label>Variety<input type="range" min={0} max={1} step={.1} value={variety} onChange={e=>setVariety(+e.target.value)}/></label><p>{variety<.3?'Favor the highest quality scores.':'Reduce repeated bursts and visually similar frames.'} Rejected photos are excluded.</p><button onClick={async()=>{const ids=await operation(()=>api.suggest(n,variety));if(ids)setSuggestions(ids)}}>Preview suggestion</button>{!!suggestions.length&&<><p>{suggestions.length} photos suggested. Review them in the grid before marking picks.</p><div className="suggest-strip">{suggestions.slice(0,10).map(id=><img key={id} src={lib?.photos.find(p=>p.id===id)?.previewUrl}/>)}</div><button className="primary" onClick={()=>{setSelected(suggestions);setActive(suggestions[0]);setGrouped(false);setFilter('all');setBest(false)}}>Review selected photos</button></>}<button onClick={()=>setBest(false)}>Cancel</button></div></div>}
 {exportOpen&&<div className="modal"><div className="lpv-dialog"><h2>Export {exportIds.length} photos</h2><p>Copies RAW and JPEG originals for picks and bookmarks. Rejected photos are excluded.</p><label>Existing filenames<select value={conflict} onChange={e=>setConflict(e.target.value as 'rename'|'skip')}><option value="rename">Rename incoming pairs</option><option value="skip">Skip conflicting pairs</option></select></label><button className="primary" onClick={()=>{setExportOpen(false);void operation(()=>api.exportPhotos(exportIds,conflict))}}>Choose destination</button><button onClick={()=>setExportOpen(false)}>Cancel</button></div></div>}
 {busy&&<div className="modal"><div className="lpv-dialog"><h2>{progress?.phase||'Preparing…'}</h2><p>{progress?.file}</p><progress max={progress?.total||1} value={progress?.current||0}/><p>{progress?.current||0} / {progress?.total||0}</p><button onClick={()=>api.cancel()}>Cancel operation</button></div></div>}
 {report&&<div className="modal"><div className="lpv-dialog"><h2>{report.title}{report.cancelled?' cancelled':' complete'}</h2><p>{report.completed} completed · {report.skipped} skipped · {report.errors.length} issues</p>{report.folder&&<p>{report.folder}</p>}<ul>{report.errors.map((e,i)=><li key={i}>{e}</li>)}</ul><button onClick={()=>setReport(null)}>Done</button></div></div>}
 {error&&<div className="error-toast" role="alert">{error}<button onClick={()=>setError('')}>Dismiss</button></div>}
 {keys&&<div className="modal"><div className="lpv-dialog"><h2>Quick culling</h2><p>← / → navigate · Enter inspect · C compare two</p><p>P pick · X reject · U clear flag · B bookmark</p><p>0–5 set stars · ⌘/Ctrl + A select visible photos</p><p>⌘/Ctrl + Z undo · Shift + ⌘/Ctrl + Z redo</p><p>Shift-click selects a range. ⌘/Ctrl-click toggles individual photos.</p><button onClick={()=>setKeys(false)}>Close</button></div></div>}
 </div>
}
