import {useEffect,useState} from 'react'
import type {Photo,Patch} from './types'
export const colors=['none','red','yellow','green','blue','purple'] as const
export function Metadata({photo:p}:{photo:Photo}){
 const shutter=p.shutter?(p.shutter>=1?`${p.shutter} s`:`1/${Math.round(1/p.shutter)} s`):'—'
 return <dl className="photo-metadata">{[['ISO',p.iso||'—'],['Shutter',shutter],['Aperture',p.aperture?`f/${p.aperture}`:'—'],['Date & time',p.capturedAt?new Date(p.capturedAt).toLocaleString():'—'],['White balance',p.whiteBalance||'Not recorded'],['Camera',p.camera||'—'],['Lens',p.lens||'—']].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>
}
export function PhotoActions({photo,change,disabled=false}:{photo?:Photo;change:(patch:Patch)=>void;disabled?:boolean}){
 return <div className="photo-actions"><button disabled={!photo||disabled} onClick={()=>change({flag:'pick'})} aria-pressed={photo?.flag==='pick'}>✓ Pick <kbd>P</kbd></button><button disabled={!photo||disabled} onClick={()=>change({flag:'reject'})} aria-pressed={photo?.flag==='reject'}>× Reject <kbd>X</kbd></button><button disabled={!photo||disabled} onClick={()=>change({flag:'none'})}>Clear flag <kbd>U</kbd></button><button disabled={!photo||disabled} onClick={()=>change({bookmarked:!photo?.bookmarked})} aria-pressed={!!photo?.bookmarked}>Bookmark <kbd>B</kbd></button><button disabled={!photo||disabled} onClick={()=>change({review:!photo?.review})} aria-pressed={!!photo?.review}>Review <kbd>R</kbd></button><label>Stars <select aria-label="Your star rating" disabled={!photo||disabled} value={photo?.stars||0} onChange={e=>change({stars:+e.target.value})}>{[0,1,2,3,4,5].map(n=><option key={n} value={n}>{n===0?'Unrated':`${n} ★`}</option>)}</select><kbd>0–5</kbd></label><label>Label <select aria-label="Color label" disabled={!photo||disabled} value={photo?.colorLabel||'none'} onChange={e=>change({colorLabel:e.target.value as Photo['colorLabel']})}>{colors.map(c=><option key={c}>{c}</option>)}</select></label></div>
}
export function Profile({photo,change}:{photo:Photo;change:(patch:Patch)=>void}){
 const [state,setState]=useState<{engine?:string;profiles:{id:string;name:string;camera:string}[]}>({profiles:[]}),[error,setError]=useState('')
 useEffect(()=>{window.photoAPI.profiles().then(setState).catch(e=>setError(e.message))},[])
 const same=(a:string,b:string)=>a.toLowerCase().replace(/^sony\s*/,'').replace(/[^a-z0-9]/g,'')===b.toLowerCase().replace(/^sony\s*/,'').replace(/[^a-z0-9]/g,'')
 const profiles=state.profiles.filter(p=>same(p.camera,photo.camera||''))
 async function configure(engine=false){try{setState(await(engine?window.photoAPI.setProfileEngine():window.photoAPI.addProfile()));setError('')}catch(e){setError((e as Error).message)}}
 return <div className="profile-control"><label>RAW viewing profile<select aria-label="RAW viewing profile" disabled={!photo.rawPath} value={photo.viewingProfile||'neutral'} onChange={e=>change({viewingProfile:e.target.value})}><option value="neutral">Neutral RAW</option><option value="camera">Camera as shot (JPEG preview)</option>{photo.viewingProfile?.startsWith('dcp:')&&!profiles.some(p=>p.id===photo.viewingProfile)&&<option value={photo.viewingProfile}>Saved profile (unavailable for this camera)</option>}{profiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button onClick={()=>configure()}>Add camera .dcp profile</button><button onClick={()=>configure(true)}>{state.engine?'Change':'Set'} RawTherapee renderer</button><small>Applies to all photos you view and stays selected until you change it. Camera-specific DCP profiles require a matching camera. </small><small>{profiles.length?profiles.length+' matching camera profiles':'No matching profiles for '+(photo.camera||'this camera')}. DCP profiles apply to RAW data. As shot uses the recorded camera JPEG. Rendering may differ from Lightroom’s overall processing.</small>{error&&<small role="alert">{error}</small>}</div>
}
